"""User переделан

Revision ID: 31ee0aefaaf2
Revises: 34e99708fc6e
Create Date: 2026-07-17 10:15:19.221792

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "31ee0aefaaf2"
down_revision: str | Sequence[str] | None = "34e99708fc6e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
