"""User переделан

Revision ID: 34e99708fc6e
Revises: 78cdce30f9ab
Create Date: 2026-07-17 10:12:25.201979

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "34e99708fc6e"
down_revision: str | Sequence[str] | None = "78cdce30f9ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
