"""added messages

Revision ID: 5b7faadd267f
Revises: b09521bb63c6
Create Date: 2026-07-16 19:09:38.667935

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5b7faadd267f"
down_revision: str | Sequence[str] | None = "b09521bb63c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
