"""added messages

Revision ID: 78cdce30f9ab
Revises: 5b7faadd267f
Create Date: 2026-07-16 19:14:38.330626

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "78cdce30f9ab"
down_revision: str | Sequence[str] | None = "5b7faadd267f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
