"""initial_migration

Revision ID: b09521bb63c6
Revises: 3e317d29cf20
Create Date: 2026-07-16 19:07:58.454877

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b09521bb63c6"
down_revision: str | Sequence[str] | None = "3e317d29cf20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
