"""initial_migration

Revision ID: e87632a0deb4
Revises: 390c53f98720
Create Date: 2026-07-16 14:12:47.976029

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e87632a0deb4"
down_revision: str | Sequence[str] | None = "390c53f98720"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
