"""fix_ai_column_location

Revision ID: eb7835f064f2
Revises: 31ee0aefaaf2
Create Date: 2026-07-18 07:56:17.178312

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb7835f064f2"
down_revision: str | Sequence[str] | None = "31ee0aefaaf2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "ai")
    op.add_column("messages", sa.Column("ai", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "ai")
    op.add_column(
        "chats", sa.Column("ai", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
